theme: jekyll-theme-midnight
title: CIT281 Project 3
description: Write node.js javascript which can find the value of coin objects and update node.js server code so that a coinCount function can be imported and used by different routes employing the "GET" verb. Practice initiallizing and using fastify.
